### ISSUE TITLE
Error in the demonstrated example (py3.5, spyder)

### ISSUE THREAD

**Issue by AbhishekHP2016** [GGiecold/DBSCAN_multiplex#6]
When I run this code:
import numpy as np
import DBSCAN_multiplex as DB
data = np.random.randn(15000, 7)
N_iterations = 50
N_sub = 9 * data.shape[0] / 10
subsamples_matrix = np.zeros((N_iterations, N_sub), dtype = float)#int)
for i in range(N_iterations): 
    subsamples_matrix[i] = np.random.choice(data.shape[0], N_sub, replace = False)
eps, labels_matrix = DB.DBSCAN(data, minPts = 3, subsamples_matrix = subsamples_matrix, verbose = True)

TypeError: 'float' object cannot be interpreted as an integer

**Comment by GGiecold-zz** [comment]
Have you tried running this program with Python 2.7?
DBSCAN_multiplex has not yet been ported to Python3.*.

Gregory


On May 30, 2017 3:37 AM, "Abhishek H P" <notifications@github.com> wrote:

When I run this code:
import numpy as np
import DBSCAN_multiplex as DB
data = np.random.randn(15000, 7)
N_iterations = 50
N_sub = 9 * data.shape[0] / 10
subsamples_matrix = np.zeros((N_iterations, N_sub), dtype = float)#int)
for i in range(N_iterations):
subsamples_matrix[i] = np.random.choice(data.shape[0], N_sub, replace =
False)
eps, labels_matrix = DB.DBSCAN(data, minPts = 3, subsamples_matrix =
subsamples_matrix, verbose = True)

TypeError: 'float' object cannot be interpreted as an integer

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GGiecold/DBSCAN_multiplex/issues/6>, or mute the thread

**Comment by kingbuuhuu** [comment]
Just add a np.ceil to N_sub and replace every xrange by range in the example and the DBSCAN_multiplex.py to make it work in python 3.
